### ISSUE TITLE
riemann output crashes logstash

### ISSUE THREAD

**Issue by jordansissel** [logstash-plugins/logstash-output-riemann#3]
(This issue was originally filed by @kosfar at https://github.com/elastic/logstash/issues/2303)

---

Hello,
i tried to use something like this (LS version 1.4.2):
output {
...some other config here...

if [proc_name] == "kernel" and [syslog_severity] != "informational" {
   riemann {
    map_fields => true
     riemann_event => {
       "service"   => "Kernel traces"
        "state"    => "%{syslog_severity}"
     }
   }
 }

...some other config here...
}

but when an event that matches reaches the riemann output, logstash crashes with the following error message:
NoMethodError: undefined method `each' for #LogStash::Event:0x55f721a9
     map_fields at /opt/logstash/lib/logstash/outputs/riemann.rb:109
        receive at /opt/logstash/lib/logstash/outputs/riemann.rb:143
         handle at /opt/logstash/lib/logstash/outputs/base.rb:86
     initialize at (eval):1698
           call at org/jruby/RubyProc.java:271
         output at /opt/logstash/lib/logstash/pipeline.rb:266
   outputworker at /opt/logstash/lib/logstash/pipeline.rb:225
  start_outputs at /opt/logstash/lib/logstash/pipeline.rb:152

We use map_fields => true so that we can further split streams per host in riemann.

Any hints?

**Comment by adnan-panalytics** [comment]
@jordansissel This issue has is the same as the NoMethodError opened by @hmrm and has already been fixed. There is a pull request pending from @venturaville. 

The error is basically due to the event being passed as an object and not as a hash of values which is what is being expected in the map_fields function. I don't know why the merge pull request is in a failed state, but if we could use the same fix and integrate it, or even better, integrate @venturaville 's changes that would be great.

**Comment by suyograo** [comment]
#5 fixes this
